name: CI for Kotlin using gradle

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main", "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      working-directory: ./HIF_FT_kotlin
      run: ./gradlew -i build --no-daemon

